/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    ArticleDetailSkeleton: typeof import('./src/components/ArticleDetailSkeleton.vue')['default']
    AsideInfoCards: typeof import('./src/components/AsideInfoCards.vue')['default']
    Comment: typeof import('./src/components/Comment/index.vue')['default']
    CommentEditor: typeof import('./src/components/Comment/CommentEditor.vue')['default']
    CommentForm: typeof import('./src/components/Comment/CommentForm.vue')['default']
    CommentItem: typeof import('./src/components/Comment/CommentItem.vue')['default']
    CommentList: typeof import('./src/components/Comment/CommentList.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    Pager: typeof import('./src/components/Pager.vue')['default']
    PreviewComment: typeof import('./src/components/Comment/PreviewComment.vue')['default']
    ReplyForm: typeof import('./src/components/Comment/ReplyForm.vue')['default']
    ReplyList: typeof import('./src/components/Comment/ReplyList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
